<h1><center>IST 597 Foundations of Deep Learning</center></h1>

---

<h2><center>Introduction to PyTorch</center><h2>
<h3><center>Neisarg Dave</center><h3>

PyTorch Tutorials:
+ https://pytorch.org/tutorials/beginner/basics/quickstart_tutorial.html
+ https://pytorch.org/tutorials/index.html


In [1]:
import torch

In [2]:
# Define Tensors:

x = torch.tensor([2,6,3,6,9,5,2,6,5,3])
print(x)
print(x.shape)
print(x.size())
print(x.device)
print(x.type())

tensor([2, 6, 3, 6, 9, 5, 2, 6, 5, 3])
torch.Size([10])
torch.Size([10])
cpu
torch.LongTensor


In [3]:
x = x.cuda()

In [4]:
print(x.device)

cuda:0


In [5]:
x = torch.tensor([2,6,3,6,9,5,2,6,5,3], dtype=torch.float, device=torch.device("cuda:0"))
print(x.type())
print(x.device)

torch.cuda.FloatTensor
cuda:0


Torch.tensor
+ https://pytorch.org/docs/stable/tensors.html
+ https://pytorch.org/docs/stable/torch.html

Also Try:
- torch.ones
- torch.zeros
- torch.nn.functional.one_hot
  + https://pytorch.org/docs/stable/generated/torch.nn.functional.one_hot.html

In [6]:
W = torch.rand([10, 1], dtype = torch.float, device = torch.device("cuda:0"), requires_grad=True)
print(W)
print(W.device)
print(W.requires_grad)

tensor([[0.5952],
        [0.3240],
        [0.1811],
        [0.4623],
        [0.2543],
        [0.3664],
        [0.0092],
        [0.1179],
        [0.2987],
        [0.0824]], device='cuda:0', requires_grad=True)
cuda:0
True


In [7]:
# matrix multiplication
z = torch.matmul(x, W)
print(z.shape)
print(z.requires_grad)

torch.Size([1])
True


Also try:
+ torch.bmm
+ torch.addbmm
+ torch.addmm
+ torch.addmv
+ torch.chain_matmul
+ torch.mm
+ torch.mv

In [8]:
 h = torch.sigmoid(z)
 print(z.requires_grad)
 print(h.requires_grad)

True
True


In [9]:
y = torch.tensor([0], dtype = torch.long, device = torch.device("cuda:0"))

In [10]:
loss = (y - h)**2
print(loss)

tensor([1.0000], device='cuda:0', grad_fn=<PowBackward0>)


In [11]:
loss.backward()

$ h = σ(xW) $ \\
\
$ loss = (y - h)^2 $ \\
\
$\frac{\partial loss}{\partial W} = \frac{\partial loss}{\partial h} \frac{\partial h}{ \partial W}$

In [12]:
print(W.grad)

tensor([[8.5830e-06],
        [2.5749e-05],
        [1.2875e-05],
        [2.5749e-05],
        [3.8624e-05],
        [2.1458e-05],
        [8.5830e-06],
        [2.5749e-05],
        [2.1458e-05],
        [1.2875e-05]], device='cuda:0')


$ \frac{\partial loss} {\partial h} = 2(y-h)$

In [13]:
with torch.no_grad():
  dldh = -2*(y - h)
  print(dldh)

tensor([2.0000], device='cuda:0')


$\frac{\partial h}{\partial W} = \sigma(Wx)(1 - \sigma(Wx))x$

In [14]:
with torch.no_grad():
  dhdw = torch.sigmoid(z)*(1-torch.sigmoid(z))*x
  print(dhdw)

tensor([4.2915e-06, 1.2875e-05, 6.4373e-06, 1.2875e-05, 1.9312e-05, 1.0729e-05,
        4.2915e-06, 1.2875e-05, 1.0729e-05, 6.4373e-06], device='cuda:0')


In [15]:
dldw = dldh * dhdw
print(dldw)

tensor([8.5830e-06, 2.5749e-05, 1.2875e-05, 2.5749e-05, 3.8624e-05, 2.1458e-05,
        8.5830e-06, 2.5749e-05, 2.1458e-05, 1.2875e-05], device='cuda:0')


In [16]:
print(W.grad)

tensor([[8.5830e-06],
        [2.5749e-05],
        [1.2875e-05],
        [2.5749e-05],
        [3.8624e-05],
        [2.1458e-05],
        [8.5830e-06],
        [2.5749e-05],
        [2.1458e-05],
        [1.2875e-05]], device='cuda:0')
