<h1><center>IST 597 Foundations of Deep Learning</center></h1>

---

<h2><center>Introduction to Numpy</center><h2>
<h3><center>Neisarg Dave</center><h3>

In [97]:
import numpy as np

In [98]:
# define a vector
x = np.array([1, 2, 3])

In [99]:
# define a matrix
W = np.array([[3, 2, 4], [2, 4, 6], [2,3,5]])

In [100]:
print(x)

[1 2 3]


In [101]:
print(W)

[[3 2 4]
 [2 4 6]
 [2 3 5]]


In [102]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [103]:
np.ones([4, 4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [104]:
np.zeros([3, 2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [105]:
x = np.array([1, 2, 3])
y = x = np.array([4, 5, 6])
x+y


array([ 8, 10, 12])

## Random Sampling

https://numpy.org/doc/stable/reference/random/index.html

In [106]:
np.random.normal(loc = 0, scale = 0.1, size = [4,5])

array([[ 1.71100066e-01, -7.13897917e-02, -6.46659157e-03,
        -4.66150268e-02, -9.29033791e-03],
       [ 6.34268038e-02,  5.50378536e-06, -2.03818404e-01,
         4.06021670e-02,  8.78503211e-02],
       [-4.43696132e-02,  1.18760653e-01,  7.12656174e-02,
         1.19635026e-01, -1.77377777e-01],
       [-3.35494347e-02, -6.17314021e-03, -4.02247704e-02,
        -6.05331414e-02, -4.60792225e-02]])

In [107]:
np.random.uniform(low=0.0, high=1.0, size=[4, 5])

array([[0.8595226 , 0.81701471, 0.33343515, 0.64740154, 0.95565829],
       [0.69681379, 0.22291312, 0.62081877, 0.73528893, 0.48313019],
       [0.57497795, 0.99375089, 0.51159714, 0.58010534, 0.88460641],
       [0.0457655 , 0.52702398, 0.3640302 , 0.43842958, 0.44845163]])

## Indexing

In [108]:
# create a tensor by randomly sampling items

y = np.random.normal(0, 0.1, [3,4,5])
print(y)
print(y.shape)

[[[-0.1711228   0.02658172 -0.28133497 -0.07690666  0.14109153]
  [ 0.07561994  0.02231689  0.07465407  0.00640283 -0.00720211]
  [ 0.12779761 -0.14025385 -0.02791568  0.02838797 -0.11175021]
  [-0.06672808 -0.0316519  -0.00106215 -0.00253687  0.06810328]]

 [[-0.14520336  0.00808997 -0.08046729  0.15211824 -0.02468366]
  [-0.06793306 -0.11030821  0.02172297 -0.09832053 -0.07435602]
  [-0.02023335  0.13150962  0.13221402  0.14342164  0.10476505]
  [-0.04510345 -0.12658497  0.0389062  -0.03009138  0.11048103]]

 [[-0.11126616  0.09568797 -0.03003255 -0.01422879  0.10955917]
  [ 0.0273842   0.00092412 -0.12609214 -0.08776315 -0.00200487]
  [ 0.046425    0.02760724  0.14665482 -0.13720168 -0.0077481 ]
  [ 0.04715569  0.09977396 -0.01863996  0.09516067 -0.08685714]]]
(3, 4, 5)


In [109]:
print(y[0])

[[-0.1711228   0.02658172 -0.28133497 -0.07690666  0.14109153]
 [ 0.07561994  0.02231689  0.07465407  0.00640283 -0.00720211]
 [ 0.12779761 -0.14025385 -0.02791568  0.02838797 -0.11175021]
 [-0.06672808 -0.0316519  -0.00106215 -0.00253687  0.06810328]]


In [110]:
print(y[0, 1])

[ 0.07561994  0.02231689  0.07465407  0.00640283 -0.00720211]


In [111]:
print(y[1, 1:-1])

[[-0.06793306 -0.11030821  0.02172297 -0.09832053 -0.07435602]
 [-0.02023335  0.13150962  0.13221402  0.14342164  0.10476505]]


In [112]:
y[1, 1:-1] > 0

array([[False, False,  True, False, False],
       [False,  True,  True,  True,  True]])

In [113]:
y[1, 1:-1][y[1, 1:-1] > 0]

array([0.02172297, 0.13150962, 0.13221402, 0.14342164, 0.10476505])

## Broadcasting
https://numpy.org/doc/stable/user/basics.broadcasting.html

In [114]:
x = np.random.normal(0, 0.1, [5])
print(x)

[ 0.1101677   0.09709929  0.07155361 -0.00952823 -0.05373875]


In [115]:
np.broadcast_to(x, [3, 5])


array([[ 0.1101677 ,  0.09709929,  0.07155361, -0.00952823, -0.05373875],
       [ 0.1101677 ,  0.09709929,  0.07155361, -0.00952823, -0.05373875],
       [ 0.1101677 ,  0.09709929,  0.07155361, -0.00952823, -0.05373875]])

In [116]:
np.broadcast_to(np.expand_dims(x, axis = 1), [5, 3])

array([[ 0.1101677 ,  0.1101677 ,  0.1101677 ],
       [ 0.09709929,  0.09709929,  0.09709929],
       [ 0.07155361,  0.07155361,  0.07155361],
       [-0.00952823, -0.00952823, -0.00952823],
       [-0.05373875, -0.05373875, -0.05373875]])

## Stacking Tensors

In [117]:
# create a list of 10 vectors

a = [np.random.randint(0, 9, size=[20]) for i in range(10)]
print(a)


[array([7, 8, 1, 1, 4, 1, 0, 5, 8, 7, 5, 6, 0, 3, 6, 2, 0, 6, 0, 7]), array([3, 7, 4, 6, 2, 7, 3, 6, 1, 4, 4, 3, 3, 7, 0, 7, 7, 7, 6, 3]), array([5, 2, 3, 6, 5, 1, 5, 7, 6, 0, 7, 2, 8, 4, 3, 4, 4, 5, 3, 0]), array([5, 1, 2, 3, 6, 7, 6, 4, 1, 4, 0, 6, 1, 7, 0, 8, 8, 8, 6, 5]), array([0, 4, 6, 5, 6, 8, 2, 4, 3, 1, 0, 4, 0, 3, 6, 8, 5, 1, 5, 5]), array([4, 8, 7, 5, 3, 6, 4, 8, 1, 8, 1, 2, 3, 6, 8, 4, 1, 7, 5, 7]), array([0, 4, 1, 3, 5, 3, 8, 1, 3, 4, 0, 0, 7, 1, 2, 2, 0, 0, 4, 3]), array([8, 8, 8, 3, 6, 4, 7, 4, 2, 8, 5, 2, 4, 2, 8, 0, 7, 7, 5, 4]), array([8, 0, 6, 5, 3, 6, 1, 0, 3, 2, 7, 6, 5, 5, 0, 8, 4, 7, 0, 2]), array([6, 1, 1, 6, 3, 1, 0, 0, 5, 2, 5, 0, 8, 3, 1, 6, 8, 1, 1, 7])]


In [118]:
print(len(a), a[0].shape)

10 (20,)


In [119]:
# stack vectors in list
stacked_0 = np.stack(a, axis=0)
print(stacked_0)
print(stacked_0.shape)

[[7 8 1 1 4 1 0 5 8 7 5 6 0 3 6 2 0 6 0 7]
 [3 7 4 6 2 7 3 6 1 4 4 3 3 7 0 7 7 7 6 3]
 [5 2 3 6 5 1 5 7 6 0 7 2 8 4 3 4 4 5 3 0]
 [5 1 2 3 6 7 6 4 1 4 0 6 1 7 0 8 8 8 6 5]
 [0 4 6 5 6 8 2 4 3 1 0 4 0 3 6 8 5 1 5 5]
 [4 8 7 5 3 6 4 8 1 8 1 2 3 6 8 4 1 7 5 7]
 [0 4 1 3 5 3 8 1 3 4 0 0 7 1 2 2 0 0 4 3]
 [8 8 8 3 6 4 7 4 2 8 5 2 4 2 8 0 7 7 5 4]
 [8 0 6 5 3 6 1 0 3 2 7 6 5 5 0 8 4 7 0 2]
 [6 1 1 6 3 1 0 0 5 2 5 0 8 3 1 6 8 1 1 7]]
(10, 20)


In [120]:
stacked_1 = np.stack(a, axis=1)
print(stacked_1)
print(stacked_1.shape)

[[7 3 5 5 0 4 0 8 8 6]
 [8 7 2 1 4 8 4 8 0 1]
 [1 4 3 2 6 7 1 8 6 1]
 [1 6 6 3 5 5 3 3 5 6]
 [4 2 5 6 6 3 5 6 3 3]
 [1 7 1 7 8 6 3 4 6 1]
 [0 3 5 6 2 4 8 7 1 0]
 [5 6 7 4 4 8 1 4 0 0]
 [8 1 6 1 3 1 3 2 3 5]
 [7 4 0 4 1 8 4 8 2 2]
 [5 4 7 0 0 1 0 5 7 5]
 [6 3 2 6 4 2 0 2 6 0]
 [0 3 8 1 0 3 7 4 5 8]
 [3 7 4 7 3 6 1 2 5 3]
 [6 0 3 0 6 8 2 8 0 1]
 [2 7 4 8 8 4 2 0 8 6]
 [0 7 4 8 5 1 0 7 4 8]
 [6 7 5 8 1 7 0 7 7 1]
 [0 6 3 6 5 5 4 5 0 1]
 [7 3 0 5 5 7 3 4 2 7]]
(20, 10)


In [121]:
print(stacked_1.transpose())

[[7 8 1 1 4 1 0 5 8 7 5 6 0 3 6 2 0 6 0 7]
 [3 7 4 6 2 7 3 6 1 4 4 3 3 7 0 7 7 7 6 3]
 [5 2 3 6 5 1 5 7 6 0 7 2 8 4 3 4 4 5 3 0]
 [5 1 2 3 6 7 6 4 1 4 0 6 1 7 0 8 8 8 6 5]
 [0 4 6 5 6 8 2 4 3 1 0 4 0 3 6 8 5 1 5 5]
 [4 8 7 5 3 6 4 8 1 8 1 2 3 6 8 4 1 7 5 7]
 [0 4 1 3 5 3 8 1 3 4 0 0 7 1 2 2 0 0 4 3]
 [8 8 8 3 6 4 7 4 2 8 5 2 4 2 8 0 7 7 5 4]
 [8 0 6 5 3 6 1 0 3 2 7 6 5 5 0 8 4 7 0 2]
 [6 1 1 6 3 1 0 0 5 2 5 0 8 3 1 6 8 1 1 7]]


In [122]:
stacked_1.transpose() == stacked_0

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True],
       [ T

## Matrix Multiplication

In [123]:
x = np.arange(10)
W = np.random.normal(0, 0.1, size = [6, 10])
print(x)
print(x.shape, W.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,) (6, 10)


In [124]:
# matrix multiplication
y = np.matmul(W, x)
print(y.shape)
print(y)

(6,)
[ 0.1474395   1.42386554  0.55114759 -1.03611098 -0.42683544  0.93016041]


In [125]:
W@x

array([ 0.1474395 ,  1.42386554,  0.55114759, -1.03611098, -0.42683544,
        0.93016041])

## Hadarmard Product

$A_{nxn} \circ B_{nxn} = \begin{bmatrix} a_{11}b_{11} & . . .&  a_{1n}b_{1n} \\ . & . & . \\ . & . & . \\ . & . & .\\ a_{n1}b_{n1} & . . .&  a_{nn}b_{nn} \end{bmatrix}$

In [126]:
# Hadamard Product : Element Wise Product
z = W*x
print(z.shape)
print(z)

(6, 10)
[[-0.         -0.0905144   0.09686381 -0.20284199  0.25378898  0.42639489
  -0.14209557 -0.14824524 -0.17333994  0.12742897]
 [-0.          0.01775192  0.33593307  0.42135623 -0.06126095  0.19335163
   0.4927573  -0.00936042 -0.39986956  0.43320632]
 [ 0.         -0.07600614  0.06514463  0.04327504  0.20507962  0.12620651
  -0.09110344 -0.13177267  0.16242659  0.24789746]
 [-0.         -0.01223712  0.22394613  0.06200381  0.4217346  -0.81341281
  -0.01369837 -0.06585219 -0.24355032 -0.59504471]
 [ 0.          0.01721931 -0.06860145  0.47637832 -0.50808232 -0.07780407
  -0.01412052 -0.1273083  -0.28239878  0.15788238]
 [ 0.         -0.07853917  0.11581434 -0.18225228  0.25438999  0.75545718
   0.01675896 -0.46197738 -0.4859525   0.99646126]]


## Outer Product

$A_{n} \times B_{m} \rightarrow C_{n \times m} = \begin{bmatrix} a_{1}b_{1} & . . .&  a_{1}b_{m} \\ . & . & . \\ . & . & . \\ . & . & .\\ a_{n}b_{1} & . . .&  a_{n}b_{m} \end{bmatrix}$

In [127]:
a = np.random.normal(0, 0.1, size = [3])
b = np.random.normal(0, 0.1, size = [4])
print(a, b)

[-0.0796339  -0.18094367  0.06282214] [-0.09136802 -0.07349466 -0.11816917 -0.17651062]


In [128]:
op = np.outer(a, b)
print(op, op.shape)

[[ 0.00727599  0.00585267  0.00941027  0.01405623]
 [ 0.01653246  0.01329839  0.02138196  0.03193848]
 [-0.00573993 -0.00461709 -0.00742364 -0.01108878]] (3, 4)


More on tensor operations : https://numpy.org/doc/stable/reference/routines.linalg.html

## Mathematical functions in numpy

https://numpy.org/doc/stable/reference/routines.math.html

In [136]:
x = np.random.uniform(0, 5, size = [10])
print(x)

[4.86557672 3.12837869 3.31259291 0.72247688 4.57832637 0.69903048
 1.3213681  4.88442749 2.30520914 3.24446875]


In [137]:
np.sin(x)

array([-0.98828969,  0.01321358, -0.17016811,  0.66124478, -0.99102706,
        0.64347585,  0.96905372, -0.98523784,  0.74222438, -0.10269473])

In [138]:
np.tanh(x)

array([0.9998812 , 0.99617243, 0.99735045, 0.61844119, 0.99978899,
       0.60375202, 0.86712375, 0.99988559, 0.98030065, 0.99696429])

In [139]:
np.round(x, 2)

array([4.87, 3.13, 3.31, 0.72, 4.58, 0.7 , 1.32, 4.88, 2.31, 3.24])

In [140]:
np.prod(x)

5627.816621899943

In [141]:
np.sum(x)

29.061855536667718

In [142]:
np.log(x)

array([ 1.58218525,  1.14051488,  1.19773124, -0.32506987,  1.52133351,
       -0.35806094,  0.27866764,  1.58605208,  0.83517141,  1.17695162])

In [143]:
np.log10(x)

array([ 0.68713432,  0.49531932,  0.52016807, -0.14117605,  0.66070675,
       -0.15550389,  0.12102382,  0.68881367,  0.36271033,  0.5111436 ])

In [144]:
np.log2(x)

array([ 2.28261082,  1.64541516,  1.72796092, -0.46897668,  2.19482031,
       -0.51657274,  0.40203243,  2.28818947,  1.20489765,  1.69798227])

In [145]:
np.exp(x)

array([129.74574405,  22.83692383,  27.45622489,   2.05952809,
        97.35132746,   2.01180127,   3.74854627, 132.21474973,
        10.02627494,  25.64808097])