<h1><center>IST 597 Foundations of Deep Learning</center></h1>

---

<h2><center>Introduction to Numpy</center><h2>
<h3><center>Neisarg Dave</center><h3>

In [1]:
import numpy as np

In [2]:
# define a vector
x = np.array([1, 2, 3])

In [3]:
# define a matrix
W = np.array([[3, 2, 4], [2, 4, 6], [2,3,5]])

In [4]:
print(x)

[1 2 3]


In [5]:
print(W)

[[3 2 4]
 [2 4 6]
 [2 3 5]]


In [22]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
np.ones([4, 4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
np.zeros([3, 2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [87]:
x = np.array([1, 2, 3])
y = x = np.array([4, 5, 6])
x+y


array([ 8, 10, 12])

## Random Sampling

https://numpy.org/doc/stable/reference/random/index.html

In [30]:
np.random.normal(loc = 0, scale = 0.1, size = [4,5])

array([[ 0.09792399, -0.05561973, -0.18165895,  0.0476302 , -0.05761593],
       [-0.04269544, -0.02897363,  0.01615999, -0.21762062, -0.05881516],
       [-0.27700908, -0.18952902, -0.12092704,  0.00461874, -0.06348213],
       [-0.25159603,  0.02443591,  0.07401597,  0.10830333, -0.10293479]])

In [27]:
np.random.uniform(low=0.0, high=1.0, size=[4, 5])

array([[0.01642085, 0.01000077, 0.33991175, 0.08146371, 0.96755369],
       [0.72189929, 0.87383717, 0.18982813, 0.46746664, 0.80365205],
       [0.98536497, 0.2169013 , 0.35684274, 0.02955119, 0.93591452],
       [0.48140022, 0.29953938, 0.24461296, 0.94251911, 0.40221726]])

## Indexing

In [32]:
# create a tensor by randomly sampling items

y = np.random.normal(0, 0.1, [3,4,5])
print(y)
print(y.shape)

[[[-0.06932308  0.1173221   0.22284167 -0.16166382  0.02708965]
  [ 0.09907556  0.08163195 -0.05847858 -0.09869772 -0.03749893]
  [ 0.02183415 -0.17935024 -0.01178139  0.09950492 -0.02606358]
  [-0.11730132 -0.24138153 -0.14526842  0.00095615 -0.1317315 ]]

 [[-0.05162138 -0.02356721  0.11508546 -0.06233772 -0.0977354 ]
  [-0.06452405 -0.11079027 -0.11346275  0.05081289  0.02279086]
  [ 0.01369849  0.00591411  0.06813791  0.09869792  0.03206879]
  [ 0.06303045  0.06593762 -0.0840211  -0.1936661  -0.07874626]]

 [[-0.08168899  0.19093288 -0.04152824  0.10063464  0.00029692]
  [-0.03721065  0.0460011   0.06611709 -0.06427834  0.23333314]
  [-0.06243708  0.20900305 -0.06675282  0.13425412 -0.01041236]
  [-0.13264352 -0.15001002 -0.1032387   0.05802558 -0.06331753]]]
(3, 4, 5)


In [33]:
print(y[0])

[[-0.06932308  0.1173221   0.22284167 -0.16166382  0.02708965]
 [ 0.09907556  0.08163195 -0.05847858 -0.09869772 -0.03749893]
 [ 0.02183415 -0.17935024 -0.01178139  0.09950492 -0.02606358]
 [-0.11730132 -0.24138153 -0.14526842  0.00095615 -0.1317315 ]]


In [34]:
print(y[0, 1])

[ 0.09907556  0.08163195 -0.05847858 -0.09869772 -0.03749893]


In [35]:
print(y[1, 1:-1])

[[-0.06452405 -0.11079027 -0.11346275  0.05081289  0.02279086]
 [ 0.01369849  0.00591411  0.06813791  0.09869792  0.03206879]]


In [36]:
y[1, 1:-1] > 0

array([[False, False, False,  True,  True],
       [ True,  True,  True,  True,  True]])

In [37]:
y[1, 1:-1][y[1, 1:-1] > 0]

array([0.05081289, 0.02279086, 0.01369849, 0.00591411, 0.06813791,
       0.09869792, 0.03206879])

## Broadcasting
https://numpy.org/doc/stable/user/basics.broadcasting.html

In [81]:
x = np.random.normal(0, 0.1, [5])
print(x)

[ 0.25459289 -0.00739592  0.13890528  0.11126302  0.00996451]


In [83]:
np.broadcast_to(x, [3, 5])


array([[ 0.25459289, -0.00739592,  0.13890528,  0.11126302,  0.00996451],
       [ 0.25459289, -0.00739592,  0.13890528,  0.11126302,  0.00996451],
       [ 0.25459289, -0.00739592,  0.13890528,  0.11126302,  0.00996451]])

In [85]:
np.broadcast_to(np.expand_dims(x, axis = 1), [5, 3])

array([[ 0.25459289,  0.25459289,  0.25459289],
       [-0.00739592, -0.00739592, -0.00739592],
       [ 0.13890528,  0.13890528,  0.13890528],
       [ 0.11126302,  0.11126302,  0.11126302],
       [ 0.00996451,  0.00996451,  0.00996451]])

## Stacking Tensors

In [38]:
# create a list of 10 vectors

a = [np.random.randint(0, 9, size=[20]) for i in range(10)]
print(a)


[array([8, 4, 8, 0, 6, 1, 3, 1, 8, 7, 1, 0, 0, 2, 4, 7, 1, 4, 7, 8]), array([6, 0, 1, 0, 4, 6, 2, 4, 7, 6, 8, 5, 5, 1, 2, 0, 5, 6, 6, 7]), array([4, 0, 3, 8, 0, 1, 2, 6, 4, 8, 7, 5, 1, 3, 2, 0, 1, 0, 1, 2]), array([1, 5, 4, 8, 8, 8, 3, 6, 1, 6, 2, 0, 5, 3, 4, 3, 5, 7, 5, 2]), array([1, 0, 5, 6, 7, 8, 1, 7, 1, 3, 7, 2, 7, 3, 5, 4, 7, 2, 5, 8]), array([4, 3, 6, 8, 5, 6, 1, 6, 6, 3, 7, 5, 1, 2, 0, 3, 2, 7, 8, 1]), array([7, 1, 7, 4, 8, 5, 5, 1, 6, 4, 3, 7, 5, 0, 7, 5, 7, 3, 2, 4]), array([0, 4, 8, 6, 8, 5, 6, 6, 1, 7, 5, 3, 4, 5, 4, 3, 8, 7, 8, 5]), array([7, 7, 2, 7, 1, 3, 3, 5, 3, 0, 6, 2, 6, 7, 7, 8, 7, 5, 2, 5]), array([1, 4, 8, 0, 8, 4, 6, 7, 8, 3, 2, 3, 0, 1, 2, 0, 3, 7, 8, 4])]


In [39]:
print(len(a), a[0].shape)

10 (20,)


In [40]:
# stack vectors in list
stacked_0 = np.stack(a, axis=0)
print(stacked_0)
print(stacked_0.shape)

[[8 4 8 0 6 1 3 1 8 7 1 0 0 2 4 7 1 4 7 8]
 [6 0 1 0 4 6 2 4 7 6 8 5 5 1 2 0 5 6 6 7]
 [4 0 3 8 0 1 2 6 4 8 7 5 1 3 2 0 1 0 1 2]
 [1 5 4 8 8 8 3 6 1 6 2 0 5 3 4 3 5 7 5 2]
 [1 0 5 6 7 8 1 7 1 3 7 2 7 3 5 4 7 2 5 8]
 [4 3 6 8 5 6 1 6 6 3 7 5 1 2 0 3 2 7 8 1]
 [7 1 7 4 8 5 5 1 6 4 3 7 5 0 7 5 7 3 2 4]
 [0 4 8 6 8 5 6 6 1 7 5 3 4 5 4 3 8 7 8 5]
 [7 7 2 7 1 3 3 5 3 0 6 2 6 7 7 8 7 5 2 5]
 [1 4 8 0 8 4 6 7 8 3 2 3 0 1 2 0 3 7 8 4]]
(10, 20)


In [11]:
stacked_1 = np.stack(a, axis=1)
print(stacked_1)
print(stacked_1.shape)

[[7 3 4 0 6 8 8 0 4 8]
 [5 7 5 6 5 4 6 3 6 2]
 [6 6 5 7 1 3 6 1 5 6]
 [4 1 6 0 2 1 3 4 1 4]
 [3 4 7 7 2 0 3 7 5 5]
 [8 6 4 6 5 8 6 1 5 5]
 [8 5 5 5 0 0 7 1 0 5]
 [6 3 1 8 8 2 0 0 6 1]
 [4 1 1 4 2 6 2 4 1 1]
 [7 5 5 6 0 8 6 7 2 2]
 [4 7 1 2 6 7 8 1 6 6]
 [3 0 5 6 6 3 4 4 4 5]
 [6 7 3 0 1 0 4 2 1 8]
 [7 5 8 5 2 8 2 8 8 2]
 [6 0 3 2 3 5 3 5 5 2]
 [0 4 8 7 4 1 0 5 5 1]
 [0 8 0 5 6 6 3 0 0 7]
 [2 0 6 4 6 0 7 2 7 2]
 [1 7 1 6 1 3 2 4 3 8]
 [3 3 6 5 5 2 1 5 6 1]]
(20, 10)


In [41]:
print(stacked_1.transpose())

[[7 5 6 4 3 8 8 6 4 7 4 3 6 7 6 0 0 2 1 3]
 [3 7 6 1 4 6 5 3 1 5 7 0 7 5 0 4 8 0 7 3]
 [4 5 5 6 7 4 5 1 1 5 1 5 3 8 3 8 0 6 1 6]
 [0 6 7 0 7 6 5 8 4 6 2 6 0 5 2 7 5 4 6 5]
 [6 5 1 2 2 5 0 8 2 0 6 6 1 2 3 4 6 6 1 5]
 [8 4 3 1 0 8 0 2 6 8 7 3 0 8 5 1 6 0 3 2]
 [8 6 6 3 3 6 7 0 2 6 8 4 4 2 3 0 3 7 2 1]
 [0 3 1 4 7 1 1 0 4 7 1 4 2 8 5 5 0 2 4 5]
 [4 6 5 1 5 5 0 6 1 2 6 4 1 8 5 5 0 7 3 6]
 [8 2 6 4 5 5 5 1 1 2 6 5 8 2 2 1 7 2 8 1]]


In [42]:
stacked_1.transpose() == stacked_0

array([[False, False, False, False, False, False, False, False, False,
         True, False, False, False, False, False, False, False, False,
        False, False],
       [False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False],
       [ True, False, False, False, False, False, False, False, False,
        False, False,  True, False, False, False, False, False, False,
         True, False],
       [False, False, False, False, False, False, False, False, False,
         True,  True, False, False, False, False, False,  True, False,
        False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False,  True, False, False,
        False, False],
       [False, False, False, False, False, False, False, False,  True,
        False,  True, False, False, False, False, False, False, False,
        False, False],
       [Fa

## Matrix Multiplication

In [16]:
x = np.arange(10)
W = np.random.normal(0, 0.1, size = [6, 10])
print(x)
print(x.shape, W.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,) (6, 10)


In [17]:
# matrix multiplication
y = np.matmul(W, x)
print(y.shape)
print(y)

(6,)
[ 1.31287537 -4.40156415  0.33488139 -2.27453716 -0.57428413  0.12830037]


In [43]:
W@x

array([ 1.31287537, -4.40156415,  0.33488139, -2.27453716, -0.57428413,
        0.12830037])

## Hadarmard Product

$A_{nxn} \circ B_{nxn} = \begin{bmatrix} a_{11}b_{11} & . . .&  a_{1n}b_{1n} \\ . & . & . \\ . & . & . \\ . & . & .\\ a_{n1}b_{n1} & . . .&  a_{nn}b_{nn} \end{bmatrix}$

In [18]:
# Hadamard Product : Element Wise Product
z = W*x
print(z.shape)
print(z)

(6, 10)
[[ 0.         -0.02957836 -0.36726467 -0.08814405 -0.37958424 -0.39617155
  -0.15242491  0.39022512  1.78741345  0.54840458]
 [ 0.          0.05473085 -0.06050651  0.3598278  -0.26482754 -0.18513333
  -0.37995272 -0.02024482 -0.88694411 -3.01851377]
 [ 0.         -0.03229319  0.38820095  0.49728357 -0.37255102 -0.32673966
  -0.26062576  0.02674517 -0.4392978   0.85415914]
 [ 0.         -0.01450818 -0.16781739  0.17590014  0.32516763 -0.32603131
  -1.56454236 -0.50483856  0.74601261 -0.94387972]
 [ 0.         -0.25818812  0.01832246 -0.35952696 -0.48921394  0.10057612
   0.56756947  0.31444193  0.03942718 -0.50769229]
 [ 0.          0.04009538  0.02449523  0.03902806 -0.26125048  0.71871143
   0.06488015 -1.06569006 -0.11009886  0.67812954]]


## Outer Product

$A_{n} \times B_{m} \rightarrow C_{n \times m} = \begin{bmatrix} a_{1}b_{1} & . . .&  a_{1}b_{m} \\ . & . & . \\ . & . & . \\ . & . & .\\ a_{n}b_{1} & . . .&  a_{n}b_{m} \end{bmatrix}$

In [49]:
a = np.random.normal(0, 0.1, size = [3])
b = np.random.normal(0, 0.1, size = [4])
print(a, b)

[ 0.15746002 -0.14747675 -0.02453363] [-0.01754361  0.06781964  0.03089739  0.03055758]


In [50]:
op = np.outer(a, b)
print(op, op.shape)

[[-0.00276242  0.01067888  0.0048651   0.0048116 ]
 [ 0.00258727 -0.01000182 -0.00455665 -0.00450653]
 [ 0.00043041 -0.00166386 -0.00075802 -0.00074969]] (3, 4)


More on tensor operations : https://numpy.org/doc/stable/reference/routines.linalg.html

## Mathematical functions in numpy

https://numpy.org/doc/stable/reference/routines.math.html

In [58]:
x = np.random.uniform(0, 5, size = [10])
print(x)

[1.14505469 3.92953208 1.97588485 0.88051298 3.57446758 0.45331059
 0.08407703 3.2247309  3.72184661 0.1283029 ]


In [59]:
np.sin(x)

array([ 0.91073269, -0.70890144,  0.91906751,  0.77106563, -0.41948229,
        0.43794416,  0.08397801, -0.08304251, -0.54823634,  0.12795118])

In [60]:
np.tanh(x)

array([0.81610916, 0.99922783, 0.96228362, 0.70667622, 0.99842983,
       0.42461651, 0.08387947, 0.99684225, 0.99883044, 0.12760348])

In [61]:
np.round(x, 2)

array([1.15, 3.93, 1.98, 0.88, 3.57, 0.45, 0.08, 3.22, 3.72, 0.13])

In [63]:
np.prod(x)

1.6422431671596907

In [64]:
np.sum(x)

19.117720209080915

In [65]:
np.log(x)

array([ 0.1354524 ,  1.36852035,  0.68101632, -0.1272506 ,  1.27381624,
       -0.79117776, -2.4760219 ,  1.17084951,  1.31421994, -2.05336141])

In [66]:
np.log10(x)

array([ 0.05882623,  0.59434084,  0.29576163, -0.05526424,  0.55321136,
       -0.34360413, -1.07532265,  0.50849348,  0.57075847, -0.89176353])

In [67]:
np.log2(x)

array([ 0.1954165 ,  1.97435753,  0.98249887, -0.18358382,  1.83772837,
       -1.14142823, -3.57214452,  1.68917878,  1.8960186 , -2.96237432])

In [68]:
np.exp(x)

array([ 3.14261321, 50.88316274,  7.21299925,  2.41213678, 35.6756214 ,
        1.57351283,  1.08771267, 25.14680636, 41.34066363,  1.13689732])